### ISSUE TITLE
Docs: Where does the field data get stored?

### ISSUE THREAD

**Issue by guettli** [MarkusH/django-dynamic-forms#27]
I read the docs, and did not find information about how the field data gets stored.

What models (database tables) hold the data which gets entered?

Could you please update the docs? 

Thank you.

**Comment by chhantyal** [comment]
They get stored here in text field https://github.com/MarkusH/django-dynamic-forms/blob/master/dynamic_forms/models.py#L155

**Comment by MarkusH** [comment]
Thank you for the report, @guettli . I would appreciate a pull request as you know best what's unclear :)

**Comment by guettli** [comment]
Thank you. All is clear now. I close this issue.
