### ISSUE TITLE
Ability to extend the possible fields set with custom fields

### ISSUE THREAD

**Issue by dcale** [MarkusH/django-dynamic-forms#30]
It would be great if one can easily extend this app with own custom fields. E.g. imagine I have a django app for storing sports results. For some reason I want to give my admin users the ability to define custom forms (thus I use this django app). Now there is a field they always need which is a dropdown with all recorded teams. Instead of manually adding all entries for every form (thus making it cumbersome to maintain) I'd like to create a new custom field type that includes data directly from the database.

**Comment by MarkusH** [comment]
That is already possible. Have a look at the [`ChoiceField`](https://github.com/MarkusH/django-dynamic-forms/blob/master/dynamic_forms/formfields.py#L197-L214)

Happy to merge a PR if you come up with a generic implementation.

**Comment by dcale** [comment]
This can be closed, but I'd suggest to add some lines of documentation on how to do this. In my usecase I had to put the app 'dynamic_forms.apps.DynamicFormsConfig' as the last one, if you don't put it as last your fields will never be loaded because the 'loading process' already completed. For the rest one can simply reuse your decorator '@dynamic_form_field' and extend from 'BaseDynamicFormField'
